### ISSUE TITLE
README references a non-existent .jar file

### ISSUE THREAD

**Issue by kmdouglass** [MStefko/ALICA#1]
The README file states in the Installation section:

```
Copy ALICA.jar into the Micro-Manager2.0/mmplugins folder.
```

However, I am unable to find the .jar in the Git repository and instead built it myself. @MStefko , do you intend to include the ALICA.jar file with the repository? If not, I would suggest a small change to the installation instructions to clarify this.

One possibility I am toying with is setting up a nightly build system for ALICA, SASS, and the ImageInjector Plugin which would allow users to download the prebuilt jars. I haven't decided yet whether this would be better than supplying the .jars in the individual repos. Are there any thoughts?

**Comment by MStefko** [comment]
Aster also asked me this same question about SASS. I currently always attach the binary to every new release, both for [SASS](https://github.com/MStefko/SASS/releases) and [ALICA](https://github.com/MStefko/ALICA/releases). I will amend the README.md to point the user to the release page.

**Comment by kmdouglass** [comment]
Great. This makes a good deal of sense. I won't worry about distributing nightly builds then. We can close this issue when the README.md is updated.

When you get a chance, can you make a similar style release of the ImageInjector plugin? I'm working on the documentation explaining how to setup the full simulation environment to test ALICA.

**Comment by MStefko** [comment]
I took the opportunity to fix some bugs in the ImageInjector, and made a [release](https://github.com/MStefko/ImageInjectorPlugin/releases). Now it should be harder (but definitely not impossible!) to break by doing something unexpected.
